const enUS: Record<string, string> = {
  // Menu
  "menu.dashboard": "Dashboard",
  "menu.group.catalog": "Catalog",
  "menu.group.traceability": "Traceability Content",
  "menu.group.growth": "Growth",
  "menu.group.channels": "Channels & Organization",
  "menu.group.governance": "Risk & Launch",
  "menu.brands": "Brands",
  "menu.products": "Products",
  "menu.skus": "SKUs",
  "menu.batches": "Production Batches",
  "menu.codes": "Codes",
  "menu.takeover": "Legacy Code Takeover",
  "menu.pages": "Pages",
  "menu.ai-assistant": "AI Assistant",
  "menu.campaigns": "Campaigns",
  "menu.benefits": "Benefits",
  "menu.integrations": "Integrations",
  "menu.connectors": "Connectors",
  "menu.analytics": "Analytics",
  "menu.stats": "Scan Stats",
  "menu.campaign-analytics": "Campaign Analytics",
  "menu.risk-dashboard": "Risk Dashboard",
  "menu.exports": "Exports",
  "menu.deep-analytics": "Deep Analytics",
  "menu.risk-center": "Risk Center",
  "menu.channels": "Channels",
  "menu.channel-portal": "Distributor Portal",
  "menu.store-portal": "Store Portal",
  "menu.risk": "Risk Center",
  "menu.members": "Members & Points",
  "menu.gmv": "GMV Attribution",
  "menu.regional": "Regional Brands",
  "menu.accounts": "Accounts",
  "menu.settings": "Settings",
  "menu.roles": "Roles & Permissions",
  "menu.compliance": "Compliance",
  "menu.tenant": "Tenant Settings",
  "menu.brand-profile": "Branding",
  "menu.custom-domain": "Custom Domain",
  "menu.audit-logs": "Audit Logs",
  "menu.agency": "Agency",
  "menu.launch-checklist": "Launch Checklist",
  "menu.pilot": "Pilot Review",
  "menu.i18n": "Translations",

  // Common
  "common.create": "Create",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.search": "Search",
  "common.loading": "Loading...",
  "common.success": "Success",
  "common.error": "Error",
  "common.name": "Name",
  "common.status": "Status",
  "common.actions": "Actions",
  "common.enabled": "Enabled",
  "common.disabled": "Disabled",
  "common.yes": "Yes",
  "common.no": "No",
  "common.total": "{n} items",
  "common.logout": "Logout",
  "common.brand": "YiMaTong",

  // Language
  "lang.zh-CN": "中文",
  "lang.en-US": "English",

  // Members
  "members.title": "Members & Points",
  "members.tab.consumers": "Consumers",
  "members.tab.rules": "Point Rules",
  "members.tab.products": "Points Shop",
  "members.consumer_id": "Consumer ID",
  "members.level": "Member Level",
  "members.points_balance": "Points Balance",
  "members.award": "Award Points",
  "members.spend": "Deduct Points",
  "members.points": "Points",
  "members.reason": "Reason",
  "members.type": "Type",
  "members.amount": "Amount",
  "members.balance": "Balance",
  "members.rule_type": "Rule Type",
  "members.daily_limit": "Daily Limit",
  "members.description": "Description",
  "members.unlimited": "Unlimited",
  "members.product_name": "Product Name",
  "members.points_cost": "Points Cost",
  "members.stock": "Stock",
  "members.claimed": "Claimed",

  // i18n
  "i18n.title": "Translation Management",
  "i18n.key": "Translation Key",
  "i18n.locale": "Locale",
  "i18n.value": "Translation Value",
  "i18n.batch_import": "Batch Import",
  "i18n.new_translation": "New Translation",
};

export default enUS;
