const zhCN: Record<string, string> = {
  // 菜单
  "menu.dashboard": "工作台",
  "menu.group.catalog": "商品资料",
  "menu.group.traceability": "溯源内容",
  "menu.group.growth": "营销增长",
  "menu.group.channels": "渠道组织",
  "menu.group.governance": "风控发布",
  "menu.brands": "品牌管理",
  "menu.products": "产品管理",
  "menu.skus": "SKU 管理",
  "menu.batches": "生产批次",
  "menu.codes": "码管理",
  "menu.pages": "页面管理",
  "menu.ai-assistant": "AI 助手",
  "menu.campaigns": "活动管理",
  "menu.benefits": "权益管理",
  "menu.integrations": "集成管理",
  "menu.connectors": "连接器",
  "menu.analytics": "数据统计",
  "menu.stats": "扫码统计",
  "menu.campaign-analytics": "活动看板",
  "menu.risk-dashboard": "风控看板",
  "menu.exports": "导出管理",
  "menu.deep-analytics": "深度分析",
  "menu.risk-center": "风控中心",
  "menu.channels": "渠道管理",
  "menu.channel-portal": "经销商入口",
  "menu.store-portal": "门店入口",
  "menu.risk": "风控中心",
  "menu.members": "会员积分",
  "menu.gmv": "GMV 归因",
  "menu.regional": "区域品牌",
  "menu.accounts": "组织账户",
  "menu.settings": "系统设置",
  "menu.roles": "角色权限",
  "menu.compliance": "合规设置",
  "menu.tenant": "租户设置",
  "menu.audit-logs": "操作日志",
  "menu.agency": "代运营",
  "menu.launch-checklist": "上线检查",
  "menu.i18n": "多语言管理",

  // 通用
  "common.create": "新建",
  "common.edit": "编辑",
  "common.delete": "删除",
  "common.save": "保存",
  "common.cancel": "取消",
  "common.confirm": "确认",
  "common.search": "搜索",
  "common.loading": "加载中...",
  "common.success": "操作成功",
  "common.error": "操作失败",
  "common.name": "名称",
  "common.status": "状态",
  "common.actions": "操作",
  "common.enabled": "启用",
  "common.disabled": "禁用",
  "common.yes": "是",
  "common.no": "否",
  "common.total": "共 {n} 条",
  "common.logout": "退出登录",
  "common.brand": "一码通",

  // 语言
  "lang.zh-CN": "中文",
  "lang.en-US": "English",

  // 会员积分
  "members.title": "会员积分",
  "members.tab.consumers": "消费者查询",
  "members.tab.rules": "积分规则",
  "members.tab.products": "积分商城",
  "members.consumer_id": "消费者 ID",
  "members.level": "会员等级",
  "members.points_balance": "积分余额",
  "members.award": "发放积分",
  "members.spend": "扣减积分",
  "members.points": "积分数",
  "members.reason": "原因",
  "members.type": "类型",
  "members.amount": "数量",
  "members.balance": "余额",
  "members.rule_type": "规则类型",
  "members.daily_limit": "每日上限",
  "members.description": "说明",
  "members.unlimited": "不限",
  "members.product_name": "商品名称",
  "members.points_cost": "积分价格",
  "members.stock": "库存",
  "members.claimed": "已兑换",

  // i18n 管理页
  "i18n.title": "多语言管理",
  "i18n.key": "翻译键",
  "i18n.locale": "语言",
  "i18n.value": "翻译内容",
  "i18n.batch_import": "批量导入",
  "i18n.new_translation": "新增翻译",
};

export default zhCN;
