"""initial schema

Revision ID: bbe51c26b82b
Revises: 
Create Date: 2026-05-28 15:27:15.746345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_api_keys_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='brandstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('campaign_risk_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('risk_rule_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_risk_rules_campaign_id'), 'campaign_risk_rules', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_risk_rules_risk_rule_id'), 'campaign_risk_rules', ['risk_rule_id'], unique=False)
    op.create_index(op.f('ix_campaign_risk_rules_tenant_id'), 'campaign_risk_rules', ['tenant_id'], unique=False)
    op.create_index('ix_campaign_risk_rules_unique', 'campaign_risk_rules', ['campaign_id', 'risk_rule_id'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.String(length=30), nullable=False),
    sa.Column('end_at', sa.String(length=30), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_index('ix_campaigns_tenant_status', 'campaigns', ['tenant_id', 'status'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_index('ix_connectors_tenant_type', 'connectors', ['tenant_id', 'connector_type'], unique=False)
    op.create_table('consumer_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('member_level', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash')
    )
    op.create_index('ix_consumer_profiles_tenant', 'consumer_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_consumer_profiles_tenant_id'), 'consumer_profiles', ['tenant_id'], unique=False)
    op.create_table('coupon_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('consumer_id', sa.String(length=100), nullable=True),
    sa.Column('distributed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_codes_pool_dist', 'coupon_codes', ['pool_id', 'distributed'], unique=False)
    op.create_index(op.f('ix_coupon_codes_pool_id'), 'coupon_codes', ['pool_id'], unique=False)
    op.create_table('coupon_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_codes', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_pools_tenant', 'coupon_pools', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_coupon_pools_tenant_id'), 'coupon_pools', ['tenant_id'], unique=False)
    op.create_table('daily_scan_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_scans', sa.Integer(), nullable=False),
    sa.Column('uv', sa.Integer(), nullable=False),
    sa.Column('first_scans', sa.Integer(), nullable=False),
    sa.Column('rescans', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_tenant_date')
    )
    op.create_index(op.f('ix_daily_scan_stats_tenant_id'), 'daily_scan_stats', ['tenant_id'], unique=False)
    op.create_table('distributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_distributors_tenant_code', 'distributors', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_distributors_tenant_id'), 'distributors', ['tenant_id'], unique=False)
    op.create_table('diversion_clues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('code_item_id', sa.Uuid(), nullable=False),
    sa.Column('expected_region', sa.String(length=200), nullable=True),
    sa.Column('detected_city', sa.String(length=100), nullable=True),
    sa.Column('distributor_id', sa.Uuid(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diversion_clues_code_item_id'), 'diversion_clues', ['code_item_id'], unique=False)
    op.create_index(op.f('ix_diversion_clues_distributor_id'), 'diversion_clues', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_diversion_clues_public_id'), 'diversion_clues', ['public_id'], unique=False)
    op.create_index(op.f('ix_diversion_clues_tenant_id'), 'diversion_clues', ['tenant_id'], unique=False)
    op.create_index('ix_diversion_clues_tenant_resolved', 'diversion_clues', ['tenant_id', 'resolved'], unique=False)
    op.create_table('external_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ext_orders_tenant_ext_id', 'external_orders', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_external_orders_phone_hash'), 'external_orders', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_external_orders_tenant_id'), 'external_orders', ['tenant_id'], unique=False)
    op.create_table('gmv_attributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_order_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gmv_attr_tenant_order', 'gmv_attributions', ['tenant_id', 'external_order_id'], unique=False)
    op.create_index(op.f('ix_gmv_attributions_external_order_id'), 'gmv_attributions', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_gmv_attributions_public_id'), 'gmv_attributions', ['public_id'], unique=False)
    op.create_index(op.f('ix_gmv_attributions_tenant_id'), 'gmv_attributions', ['tenant_id'], unique=False)
    op.create_table('interception_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('risk_rule_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('consumer_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interception_records_campaign_id'), 'interception_records', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_interception_records_risk_rule_id'), 'interception_records', ['risk_rule_id'], unique=False)
    op.create_index(op.f('ix_interception_records_tenant_id'), 'interception_records', ['tenant_id'], unique=False)
    op.create_index('ix_interceptions_tenant_rule', 'interception_records', ['tenant_id', 'risk_rule_id'], unique=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_records_account_id'), 'kyc_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_kyc_records_tenant_id'), 'kyc_records', ['tenant_id'], unique=False)
    op.create_index('ix_kyc_tenant_account', 'kyc_records', ['tenant_id', 'account_id'], unique=False)
    op.create_table('page_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_templates_product_id'), 'page_templates', ['product_id'], unique=False)
    op.create_index(op.f('ix_page_templates_tenant_id'), 'page_templates', ['tenant_id'], unique=False)
    op.create_table('page_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('page_template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_versions_page_template_id'), 'page_versions', ['page_template_id'], unique=False)
    op.create_index(op.f('ix_page_versions_tenant_id'), 'page_versions', ['tenant_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_tenant_id'), 'permissions', ['tenant_id'], unique=False)
    op.create_table('platform_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('target_tenant_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_rules_tenant_id'), 'point_rules', ['tenant_id'], unique=False)
    op.create_index('ix_point_rules_tenant_type', 'point_rules', ['tenant_id', 'rule_type'], unique=True)
    op.create_table('point_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_point_transactions_consumer', 'point_transactions', ['tenant_id', 'consumer_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_consumer_id'), 'point_transactions', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_tenant_id'), 'point_transactions', ['tenant_id'], unique=False)
    op.create_table('redpacket_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redpacket_claims_account_id'), 'redpacket_claims', ['account_id'], unique=False)
    op.create_index('ix_redpacket_claims_rule_account', 'redpacket_claims', ['rule_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_redpacket_claims_rule_id'), 'redpacket_claims', ['rule_id'], unique=False)
    op.create_index(op.f('ix_redpacket_claims_tenant_id'), 'redpacket_claims', ['tenant_id'], unique=False)
    op.create_table('redpacket_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_budget', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('daily_limit_per_user', sa.Integer(), nullable=False),
    sa.Column('single_limit_per_user', sa.Integer(), nullable=False),
    sa.Column('require_kyc', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_budget', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_redpacket_rules_tenant', 'redpacket_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_redpacket_rules_tenant_id'), 'redpacket_rules', ['tenant_id'], unique=False)
    op.create_table('regional_code_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_code_rules_org_id'), 'regional_code_rules', ['org_id'], unique=False)
    op.create_table('regional_org_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regional_org_member_unique', 'regional_org_members', ['org_id', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_regional_org_members_org_id'), 'regional_org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_regional_org_members_tenant_id'), 'regional_org_members', ['tenant_id'], unique=False)
    op.create_table('regional_orgs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regional_orgs_tenant', 'regional_orgs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_regional_orgs_tenant_id'), 'regional_orgs', ['tenant_id'], unique=False)
    op.create_table('regional_product_auths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regional_product_auth_unique', 'regional_product_auths', ['org_id', 'product_id', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_regional_product_auths_org_id'), 'regional_product_auths', ['org_id'], unique=False)
    op.create_index(op.f('ix_regional_product_auths_product_id'), 'regional_product_auths', ['product_id'], unique=False)
    op.create_index(op.f('ix_regional_product_auths_tenant_id'), 'regional_product_auths', ['tenant_id'], unique=False)
    op.create_table('regional_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_templates_org_id'), 'regional_templates', ['org_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('code_item_id', sa.Uuid(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_alert_type'), 'risk_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_risk_alerts_code_item_id'), 'risk_alerts', ['code_item_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_public_id'), 'risk_alerts', ['public_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_tenant_id'), 'risk_alerts', ['tenant_id'], unique=False)
    op.create_index('ix_risk_alerts_tenant_resolved', 'risk_alerts', ['tenant_id', 'resolved'], unique=False)
    op.create_index('ix_risk_alerts_tenant_type', 'risk_alerts', ['tenant_id', 'alert_type'], unique=False)
    op.create_table('risk_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rules_rule_type'), 'risk_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_risk_rules_tenant_id'), 'risk_rules', ['tenant_id'], unique=False)
    op.create_index('ix_risk_rules_tenant_type', 'risk_rules', ['tenant_id', 'rule_type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_first_scan', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_public_id'), 'scan_events', ['public_id'], unique=False)
    op.create_index(op.f('ix_scan_events_tenant_id'), 'scan_events', ['tenant_id'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_records_tenant_id'), 'sync_records', ['tenant_id'], unique=False)
    op.create_index('ix_sync_records_tenant_type', 'sync_records', ['tenant_id', 'sync_type'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'terminated', name='tenantstatus'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', 'enterprise', name='tenantplan'), nullable=False),
    sa.Column('quota', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_tenant_id'), 'translations', ['tenant_id'], unique=False)
    op.create_index('ix_translations_tenant_key_locale', 'translations', ['tenant_id', 'key', 'locale'], unique=True)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_deliveries_tenant', 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_endpoints_tenant', 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_table('whitelabel_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('hide_yimatong', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_account_id'), 'withdrawals', ['account_id'], unique=False)
    op.create_index('ix_withdrawals_tenant_account', 'withdrawals', ['tenant_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_tenant_id'), 'withdrawals', ['tenant_id'], unique=False)
    op.create_table('benefits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('benefit_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_used', sa.Integer(), nullable=False),
    sa.Column('per_person_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_campaign_id'), 'benefits', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_benefits_tenant_id'), 'benefits', ['tenant_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'draft', name='productstatus'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('distributor_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_distributor_id'), 'regions', ['distributor_id'], unique=False)
    op.create_index('ix_regions_tenant_code', 'regions', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_regions_tenant_id'), 'regions', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_organization_id'), 'accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('benefit_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('benefit_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefit_id', 'consumer_id', 'idempotency_key', name='uq_claim_idempotent')
    )
    op.create_index(op.f('ix_benefit_claims_benefit_id'), 'benefit_claims', ['benefit_id'], unique=False)
    op.create_index('ix_benefit_claims_campaign_consumer', 'benefit_claims', ['campaign_id', 'consumer_id'], unique=False)
    op.create_index(op.f('ix_benefit_claims_campaign_id'), 'benefit_claims', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_benefit_claims_tenant_id'), 'benefit_claims', ['tenant_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='skustatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_product_id'), 'skus', ['product_id'], unique=False)
    op.create_index(op.f('ix_skus_tenant_id'), 'skus', ['tenant_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('distributor_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_distributor_id'), 'stores', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_stores_region_id'), 'stores', ['region_id'], unique=False)
    op.create_index('ix_stores_tenant_code', 'stores', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_stores_tenant_id'), 'stores', ['tenant_id'], unique=False)
    op.create_table('account_roles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'role_id')
    )
    op.create_table('code_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'completed', 'failed', name='codebatchstatus'), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_batches_distributor_id'), 'code_batches', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_code_batches_product_id'), 'code_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_code_batches_region_id'), 'code_batches', ['region_id'], unique=False)
    op.create_index(op.f('ix_code_batches_sku_id'), 'code_batches', ['sku_id'], unique=False)
    op.create_index('ix_code_batches_tenant_batch', 'code_batches', ['tenant_id', 'batch_code'], unique=False)
    op.create_index(op.f('ix_code_batches_tenant_id'), 'code_batches', ['tenant_id'], unique=False)
    op.create_table('production_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'recalled', 'expired', name='batchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_product_id'), 'production_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_batches_sku_id'), 'production_batches', ['sku_id'], unique=False)
    op.create_index(op.f('ix_production_batches_tenant_id'), 'production_batches', ['tenant_id'], unique=False)
    op.create_table('code_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code_batch_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('created', 'activated', 'bound', 'expired', 'revoked', 'frozen', name='codeitemstatus'), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('pair_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('bound_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_batch_id'], ['code_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_code_items_code_batch_id'), 'code_items', ['code_batch_id'], unique=False)
    op.create_index('ix_code_items_pair', 'code_items', ['pair_id'], unique=False)
    op.create_index(op.f('ix_code_items_pair_id'), 'code_items', ['pair_id'], unique=False)
    op.create_index('ix_code_items_tenant_batch', 'code_items', ['tenant_id', 'code_batch_id'], unique=False)
    op.create_index(op.f('ix_code_items_tenant_id'), 'code_items', ['tenant_id'], unique=False)
    op.create_index('ix_code_items_tenant_status', 'code_items', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_items_tenant_status', table_name='code_items')
    op.drop_index(op.f('ix_code_items_tenant_id'), table_name='code_items')
    op.drop_index('ix_code_items_tenant_batch', table_name='code_items')
    op.drop_index(op.f('ix_code_items_pair_id'), table_name='code_items')
    op.drop_index('ix_code_items_pair', table_name='code_items')
    op.drop_index(op.f('ix_code_items_code_batch_id'), table_name='code_items')
    op.drop_table('code_items')
    op.drop_index(op.f('ix_production_batches_tenant_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_sku_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_product_id'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index(op.f('ix_code_batches_tenant_id'), table_name='code_batches')
    op.drop_index('ix_code_batches_tenant_batch', table_name='code_batches')
    op.drop_index(op.f('ix_code_batches_sku_id'), table_name='code_batches')
    op.drop_index(op.f('ix_code_batches_region_id'), table_name='code_batches')
    op.drop_index(op.f('ix_code_batches_product_id'), table_name='code_batches')
    op.drop_index(op.f('ix_code_batches_distributor_id'), table_name='code_batches')
    op.drop_table('code_batches')
    op.drop_table('account_roles')
    op.drop_index(op.f('ix_stores_tenant_id'), table_name='stores')
    op.drop_index('ix_stores_tenant_code', table_name='stores')
    op.drop_index(op.f('ix_stores_region_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_distributor_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_skus_tenant_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_product_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_benefit_claims_tenant_id'), table_name='benefit_claims')
    op.drop_index(op.f('ix_benefit_claims_campaign_id'), table_name='benefit_claims')
    op.drop_index('ix_benefit_claims_campaign_consumer', table_name='benefit_claims')
    op.drop_index(op.f('ix_benefit_claims_benefit_id'), table_name='benefit_claims')
    op.drop_table('benefit_claims')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_organization_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_regions_tenant_id'), table_name='regions')
    op.drop_index('ix_regions_tenant_code', table_name='regions')
    op.drop_index(op.f('ix_regions_distributor_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_benefits_tenant_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_campaign_id'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_withdrawals_tenant_id'), table_name='withdrawals')
    op.drop_index('ix_withdrawals_tenant_account', table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_account_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_table('whitelabel_configs')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_index('ix_webhook_endpoints_tenant', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_tenant', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_translations_tenant_key_locale', table_name='translations')
    op.drop_index(op.f('ix_translations_tenant_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_table('tenants')
    op.drop_index('ix_sync_records_tenant_type', table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_tenant_id'), table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_scan_events_tenant_id'), table_name='scan_events')
    op.drop_index(op.f('ix_scan_events_public_id'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_risk_rules_tenant_type', table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_tenant_id'), table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_rule_type'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index('ix_risk_alerts_tenant_type', table_name='risk_alerts')
    op.drop_index('ix_risk_alerts_tenant_resolved', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_tenant_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_public_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_code_item_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_alert_type'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_regional_templates_org_id'), table_name='regional_templates')
    op.drop_table('regional_templates')
    op.drop_index(op.f('ix_regional_product_auths_tenant_id'), table_name='regional_product_auths')
    op.drop_index(op.f('ix_regional_product_auths_product_id'), table_name='regional_product_auths')
    op.drop_index(op.f('ix_regional_product_auths_org_id'), table_name='regional_product_auths')
    op.drop_index('ix_regional_product_auth_unique', table_name='regional_product_auths')
    op.drop_table('regional_product_auths')
    op.drop_index(op.f('ix_regional_orgs_tenant_id'), table_name='regional_orgs')
    op.drop_index('ix_regional_orgs_tenant', table_name='regional_orgs')
    op.drop_table('regional_orgs')
    op.drop_index(op.f('ix_regional_org_members_tenant_id'), table_name='regional_org_members')
    op.drop_index(op.f('ix_regional_org_members_org_id'), table_name='regional_org_members')
    op.drop_index('ix_regional_org_member_unique', table_name='regional_org_members')
    op.drop_table('regional_org_members')
    op.drop_index(op.f('ix_regional_code_rules_org_id'), table_name='regional_code_rules')
    op.drop_table('regional_code_rules')
    op.drop_index(op.f('ix_redpacket_rules_tenant_id'), table_name='redpacket_rules')
    op.drop_index('ix_redpacket_rules_tenant', table_name='redpacket_rules')
    op.drop_table('redpacket_rules')
    op.drop_index(op.f('ix_redpacket_claims_tenant_id'), table_name='redpacket_claims')
    op.drop_index(op.f('ix_redpacket_claims_rule_id'), table_name='redpacket_claims')
    op.drop_index('ix_redpacket_claims_rule_account', table_name='redpacket_claims')
    op.drop_index(op.f('ix_redpacket_claims_account_id'), table_name='redpacket_claims')
    op.drop_table('redpacket_claims')
    op.drop_index(op.f('ix_point_transactions_tenant_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_consumer_id'), table_name='point_transactions')
    op.drop_index('ix_point_transactions_consumer', table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index('ix_point_rules_tenant_type', table_name='point_rules')
    op.drop_index(op.f('ix_point_rules_tenant_id'), table_name='point_rules')
    op.drop_table('point_rules')
    op.drop_table('platform_audit_log')
    op.drop_index(op.f('ix_permissions_tenant_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_page_versions_tenant_id'), table_name='page_versions')
    op.drop_index(op.f('ix_page_versions_page_template_id'), table_name='page_versions')
    op.drop_table('page_versions')
    op.drop_index(op.f('ix_page_templates_tenant_id'), table_name='page_templates')
    op.drop_index(op.f('ix_page_templates_product_id'), table_name='page_templates')
    op.drop_table('page_templates')
    op.drop_index('ix_kyc_tenant_account', table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_tenant_id'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_account_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_index('ix_interceptions_tenant_rule', table_name='interception_records')
    op.drop_index(op.f('ix_interception_records_tenant_id'), table_name='interception_records')
    op.drop_index(op.f('ix_interception_records_risk_rule_id'), table_name='interception_records')
    op.drop_index(op.f('ix_interception_records_campaign_id'), table_name='interception_records')
    op.drop_table('interception_records')
    op.drop_index(op.f('ix_gmv_attributions_tenant_id'), table_name='gmv_attributions')
    op.drop_index(op.f('ix_gmv_attributions_public_id'), table_name='gmv_attributions')
    op.drop_index(op.f('ix_gmv_attributions_external_order_id'), table_name='gmv_attributions')
    op.drop_index('ix_gmv_attr_tenant_order', table_name='gmv_attributions')
    op.drop_table('gmv_attributions')
    op.drop_index(op.f('ix_external_orders_tenant_id'), table_name='external_orders')
    op.drop_index(op.f('ix_external_orders_phone_hash'), table_name='external_orders')
    op.drop_index('ix_ext_orders_tenant_ext_id', table_name='external_orders')
    op.drop_table('external_orders')
    op.drop_index('ix_diversion_clues_tenant_resolved', table_name='diversion_clues')
    op.drop_index(op.f('ix_diversion_clues_tenant_id'), table_name='diversion_clues')
    op.drop_index(op.f('ix_diversion_clues_public_id'), table_name='diversion_clues')
    op.drop_index(op.f('ix_diversion_clues_distributor_id'), table_name='diversion_clues')
    op.drop_index(op.f('ix_diversion_clues_code_item_id'), table_name='diversion_clues')
    op.drop_table('diversion_clues')
    op.drop_index(op.f('ix_distributors_tenant_id'), table_name='distributors')
    op.drop_index('ix_distributors_tenant_code', table_name='distributors')
    op.drop_table('distributors')
    op.drop_index(op.f('ix_daily_scan_stats_tenant_id'), table_name='daily_scan_stats')
    op.drop_table('daily_scan_stats')
    op.drop_index(op.f('ix_coupon_pools_tenant_id'), table_name='coupon_pools')
    op.drop_index('ix_coupon_pools_tenant', table_name='coupon_pools')
    op.drop_table('coupon_pools')
    op.drop_index(op.f('ix_coupon_codes_pool_id'), table_name='coupon_codes')
    op.drop_index('ix_coupon_codes_pool_dist', table_name='coupon_codes')
    op.drop_table('coupon_codes')
    op.drop_index(op.f('ix_consumer_profiles_tenant_id'), table_name='consumer_profiles')
    op.drop_index('ix_consumer_profiles_tenant', table_name='consumer_profiles')
    op.drop_table('consumer_profiles')
    op.drop_index('ix_connectors_tenant_type', table_name='connectors')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index('ix_campaigns_tenant_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_campaign_risk_rules_unique', table_name='campaign_risk_rules')
    op.drop_index(op.f('ix_campaign_risk_rules_tenant_id'), table_name='campaign_risk_rules')
    op.drop_index(op.f('ix_campaign_risk_rules_risk_rule_id'), table_name='campaign_risk_rules')
    op.drop_index(op.f('ix_campaign_risk_rules_campaign_id'), table_name='campaign_risk_rules')
    op.drop_table('campaign_risk_rules')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_tenant', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
