"""add created_at updated_at to all missing models

Revision ID: 49a714248b9e
Revises: a2bbf97236e0
Create Date: 2026-06-05T20:48:11.244897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49a714248b9e'
down_revision: Union[str, None] = 'a2bbf97236e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('agency_authorizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('campaign_risk_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('campaign_risk_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('code_allocations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('code_allocations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('code_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('code_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('consumer_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('consumer_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('coupon_codes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('coupon_codes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('coupon_pools', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('coupon_pools', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('daily_scan_stats', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('daily_scan_stats', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('diversion_clues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('diversion_clues', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('external_orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('external_orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gmv_attributions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gmv_attributions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gmv_daily_stats', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('gmv_daily_stats', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('interception_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('interception_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('platform_audit_log', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('point_redemptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('point_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('point_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_assets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_code_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_code_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_org_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_org_members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_orgs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_orgs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_product_auths', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_product_auths', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('regional_templates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_alerts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('risk_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('scan_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('scan_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('skus', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('skus', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sync_mappings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sync_mappings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sync_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sync_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenant_domains', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenant_domains', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('translations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('translations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('whitelabel_configs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('whitelabel_configs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))


def downgrade() -> None:
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_column('agency_authorizations', 'updated_at')
    op.drop_column('campaign_risk_rules', 'updated_at')
    op.drop_column('campaign_risk_rules', 'created_at')
    op.drop_column('code_allocations', 'updated_at')
    op.drop_column('code_allocations', 'created_at')
    op.drop_column('code_items', 'updated_at')
    op.drop_column('code_items', 'created_at')
    op.drop_column('consumer_profiles', 'updated_at')
    op.drop_column('consumer_profiles', 'created_at')
    op.drop_column('coupon_codes', 'updated_at')
    op.drop_column('coupon_codes', 'created_at')
    op.drop_column('coupon_pools', 'updated_at')
    op.drop_column('coupon_pools', 'created_at')
    op.drop_column('daily_scan_stats', 'updated_at')
    op.drop_column('daily_scan_stats', 'created_at')
    op.drop_column('diversion_clues', 'updated_at')
    op.drop_column('diversion_clues', 'created_at')
    op.drop_column('external_orders', 'updated_at')
    op.drop_column('external_orders', 'created_at')
    op.drop_column('gmv_attributions', 'updated_at')
    op.drop_column('gmv_attributions', 'created_at')
    op.drop_column('gmv_daily_stats', 'updated_at')
    op.drop_column('gmv_daily_stats', 'created_at')
    op.drop_column('interception_records', 'updated_at')
    op.drop_column('interception_records', 'created_at')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_column('platform_audit_log', 'updated_at')
    op.drop_column('point_redemptions', 'updated_at')
    op.drop_column('point_rules', 'updated_at')
    op.drop_column('point_rules', 'created_at')
    op.drop_column('product_assets', 'updated_at')
    op.drop_column('product_assets', 'created_at')
    op.drop_column('regional_code_rules', 'updated_at')
    op.drop_column('regional_code_rules', 'created_at')
    op.drop_column('regional_org_members', 'updated_at')
    op.drop_column('regional_org_members', 'created_at')
    op.drop_column('regional_orgs', 'updated_at')
    op.drop_column('regional_orgs', 'created_at')
    op.drop_column('regional_product_auths', 'updated_at')
    op.drop_column('regional_product_auths', 'created_at')
    op.drop_column('regional_templates', 'updated_at')
    op.drop_column('regional_templates', 'created_at')
    op.drop_column('risk_alerts', 'updated_at')
    op.drop_column('risk_alerts', 'created_at')
    op.drop_column('risk_notifications', 'updated_at')
    op.drop_column('risk_notifications', 'created_at')
    op.drop_column('risk_rules', 'updated_at')
    op.drop_column('risk_rules', 'created_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('scan_events', 'updated_at')
    op.drop_column('scan_events', 'created_at')
    op.drop_column('skus', 'updated_at')
    op.drop_column('skus', 'created_at')
    op.drop_column('sync_mappings', 'updated_at')
    op.drop_column('sync_mappings', 'created_at')
    op.drop_column('sync_records', 'updated_at')
    op.drop_column('sync_records', 'created_at')
    op.drop_column('tenant_domains', 'updated_at')
    op.drop_column('tenant_domains', 'created_at')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('translations', 'updated_at')
    op.drop_column('translations', 'created_at')
    op.drop_column('whitelabel_configs', 'updated_at')
    op.drop_column('whitelabel_configs', 'created_at')
