"""add_code_item_first_scanned_at_and_scan_event_indexes

Revision ID: ebaa492c1b1e
Revises: f1099afc4241
Create Date: 2026-06-08 16:48:48.659335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaa492c1b1e'
down_revision: Union[str, None] = 'f1099afc4241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_items', sa.Column('first_scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_scan_events_public_id', 'scan_events', ['public_id'], unique=False)
    op.create_index('ix_scan_events_tenant_time', 'scan_events', ['tenant_id', 'scan_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_events_tenant_time', table_name='scan_events')
    op.drop_index('ix_scan_events_public_id', table_name='scan_events')
    op.drop_column('code_items', 'first_scanned_at')
    # ### end Alembic commands ###
